### ISSUE TITLE
[suggestion] Move Torrent support from clients to JMMServer. Also make ShanaProject the default torrent provider.

### ISSUE THREAD

**Issue by maxpiva** [japanesemediamanager/ShokoServer#129] opened 2015-02-11 17:15 UTC
1) Move utorrent functionality from Clients to JMMServer.
2) Simplify Torrent interaction, instead of adding clients, (BAKA, Nyaa, Tokyotosho, etc) and search on them. Use shana project as rss torrent provider. Auto Fetching marked shows and simplify searching, probably remove any uTorrent information and or interaction. Only Settings like uTorrent ip, etc.

**Comment by maxpiva** [comment] 2015-02-11 18:21
if approved, i might take it ;)

**Comment by jmediamanager** [comment] 2015-02-11 22:20
Sounds good.
The only problem i have is the sole reliance on ShanaProject.
But as long as we don't delete the code, we can always restore it in the future if ShanaProject goes offline.

**Comment by jmediamanager** [comment] 2015-02-11 22:27
Having said that, I wouldn't want to remove support for private trackers like BakaBT or AnimeBytes

**Comment by maxpiva** [comment] 2015-02-12 01:33
I mean, not remove any already done functionality, it can use the search a
select items to download from all already added torrent sites, what i mean,
is simplify the usage with shana project like search, select and forget,
(series will always be download automagically) or select an existing anime,
and press follow serie, and do the same magic.

**Comment by XellossMetallium** [comment] 2015-04-12 09:37
Hi there! I am a new user and I was slowly discovering all the useful features of JMM. Actually thanks to this issue I found the nice ShanaProject, a great help indeed!
Anyway, the download part is very intresting, but I noticed (or at least so it seems) that the only actual way to download via torrent is using uTorrent, which I discarded some times ago: too much ad-were and useless services. 
Actually I think that adding support for more than one torrent client would be troublesome, but a nice workaround would be to simply allow the user to choose a download folder for the torrent file, which would be the watched folder for the torrent client of choice. 
Since I'm new and not very pratical with JMM I don't feel confortable opening right off the bat a new issue without confirmation, so if you think this is a reasonable request please tell me so and I will propose it in the proper way. Thanks!

**Comment by jmediamanager** [comment] 2015-04-16 02:09
Yup I think someone else also suggested that same sort of functionality somewhere else, so that is a possibility. No need to open a new issue though, will take it into consideration here

**Comment by XellossMetallium** [comment] 2015-04-18 12:35
Awesome, thanks!

**Comment by maxpiva** [comment] 2015-04-18 20:55
I was thinking of separating plugin functionality in 4 interface types and
make it more generic. utorrent progress functionality might be loss. :(,
but there is already a lots of program/web that show your utorrent progress.

Download News plugins -> Will  list of titles, sizes, date, etc, download
link or data & download types. (Example types, torrent, nzb, xdcc info)
Search plugins -> from a search text, will return a list of titles, sizes,
date, etc, download link or data & download types. (Example types, torrent,
nzb, xdcc info)
Download plugins -> Will accept and download link/data and download type.
Follow plugins -> Example will be shana project.

Probably they will share a new AutheticationInfo contract.

**Comment by AreFinstad** [comment] 2015-04-18 21:54
just a heads up as a Seedbox user. you should think of a way to use the Seedbox Apis for us that use it.

i for one use Shana as an RSS feed and use my Seedbox ( put.io ) as a torrentclient and then take it from there with Direct Downloads with JDownloader (one of the better DDL clients IMO)

for JMM to be perfect for my usage it should hook into the seedbox, get the download links and then packaging them as a JDownloader file with file renameing embedded into it.

also talking about Torrents and such we should have a hook for Popcorntime to open .torrent/magnetlink in Popcorn for direct streaming. (if people are into that sort of things..... mostly HorribleSubs and a few others got the seeders for that tho depending on bitrate of the files)

**Comment by maxpiva** [comment] 2015-09-01 23:52
Ok. I dropped this for a better solution. Please all, check this and tell me your thoughts....

http://anidb.net/perl-bin/animedb.pl?show=cmt&id=55091

The software itself is a library, and can be easy included in other software.

**Comment by jmediamanager** [comment] 2015-09-02 00:01
This is what I have really been looking for.
I have had a CrunchyRoll account twice in the past, but have dropped my subscription each time because it is just so hard to maange what you have watched etc.

My Ideal usage for JMM is to allow a mix of files and online hosting.
That is why I have mentioned in the past allowing the web cache to map Crunchy Roll.
You could just browse via JMM desktop (recommendations, new series etc) and watch an episode, without needed to download it first.

I would still use blu-ray versions etc, but you have the options for both.

**Comment by AreFinstad** [comment] 2015-09-02 00:04
even with a program like this you are very limited to the selection of what they give to your area. like the EU Roll its bad, really bad and isnt worth the money at all. ofc a VPN fixes this..... but at that point its just easier to do Shana Torrents with Horriblesubs or something IMO. 

also, whhy move away from Shana? its a great place as it has feeds on BD content aswell as Good quality TV Subs aswell (not Roll Subs)

**Comment by ElementalCrisis** [comment] 2015-09-02 00:05
Maybe I'm reading it wrong but are you suggesting that JMM scrape the metadata from your CrunchyRoll account which is then added to your collection?

**Comment by AreFinstad** [comment] 2015-09-02 00:08
well the AniDB link entails that you can save the Streams from Different sites, which IMO isnt that great. (too many ifs for it to work perfectly for everyone every time, tho ofc they could skip the hole crc hashes and just use name parsing as it will download from the same place every time)
 
+ i have had good success with popcorntime and horrible for CrunchyRoll to even be on my map.

**Comment by jmediamanager** [comment] 2015-09-02 00:11
No, the point is that you can actually watch streams from CrunchyRoll, but using JMM Desktop or AnimeBuddy.

So you let JMM and AniDB manage your collection (faves, watched sates etc), but stream from CR.
Just replacing files with streams.

Of course JMM would need to handle both.
I have looked at this in the past quite a few times, and even requested an API from CR.
AniDB supports adding generic files, and watched states for those files.

The point is that (for people like me) who now download every Horrible/Commie release but only watch a couple of episodes a week, you just stream it instead. Saves on a huge amount of bandwidth.
For people who don't want CR, it has no effect on them.

**Comment by maxpiva** [comment] 2015-09-02 00:16
Currently it does, this, you can browser all plugin catalog and download shows or episodes, and you can set follows, and, when a new episode arrives it'll automatically download it. It also include all subtitles languages found, and mux it in a way, every episode/resolution combo has the same hash, not caring about the user or the time when you do it. (output can be mkv or mp4). The main problem here, is legality since its remove DRM when rippinng. USA for sure is no go, for hosting it.

**Comment by ElementalCrisis** [comment] 2015-09-02 00:17
Even though I don't have a CR account I think this is a great idea as it just adds more functionality to JMM. I would leave out any functionality that allows you to rip streams though, could lead to legal problems.

**Comment by maxpiva** [comment] 2015-09-02 00:19
Currently it has a standalone client using the library. Not JMM.

**Comment by AreFinstad** [comment] 2015-09-02 00:19
sounds fair, this is something that JMM can have great use of. i guess we need a server in Sweden, Norway or Netherlands then if we have to host the files for this.

i might actually use this if its worked into JMM..... now if only i could get One Piece on CR from Norway :/

**Comment by jmediamanager** [comment] 2015-09-02 00:22
Well for auto downloading that could be an option in JMM as well if someone prefers it over using something like Shana (personally I would keep using Shana).

However for On Demand streaming, I would definitely find it useful.

Does it download streams as fast as you connection can handle?

**Comment by AreFinstad** [comment] 2015-09-02 00:22
@maxpiva got a link for the site? as i can't seem to find it, no link on the AniDB page and no user named the same either here on Git, no name for the plugin either..... maybe im just blind XD

**Comment by AreFinstad** [comment] 2015-09-02 00:23
well i think they would have the same limits as the CR streams themselfs..... ofc i might be wrong here.

**Comment by maxpiva** [comment] 2015-09-02 00:26
Site? i don't understand. Yepz the limit is imposed by the host. But here i'm downloading it like 3 to 4 times faster than viewing it. I could try to pipe an mp4/flv. realtime mkv is nono, since mkv conversion is a post processing

**Comment by AreFinstad** [comment] 2015-09-02 00:27
well you said: "Currently it has a standalone client "
so where can we get it? as i have no idea whats its even called as the AniDB thread did not say

**Comment by maxpiva** [comment] 2015-09-02 00:29
I just code it, never release it. (Client need tweaking, for should be done in one or two days). I'm asking also for ideas of how to release it. Without having a takedown notice on my door.

**Comment by jmediamanager** [comment] 2015-09-02 00:33
I think that if you have a CR account and it is just letting you watch what you are already allowed to watch it should be a problem.
I guess the issue is saving it to disk, but if you are just piping/streaming it shouldn't be an issue.

Let me know when I can have access to the library ;)

**Comment by maxpiva** [comment] 2015-09-02 00:36
Problem with streaming, is muxing the subtitles in realtime. Since crunchyroll uses a custom solution, and Daisuki TTML. Let me sit on it. I'll fix the client, and do some testing since i refactored part of the library. Then access :)

**Comment by AreFinstad** [comment] 2015-09-02 00:37
well laws the different everywhere, also their TOS also got rules for usage that can get you banned or worse. 

in alot of countries its legal to download anything you own, but then again you dont really own it as you are paying for a sub. 

and saving to disk should be any worse that just using Fraps or whatever to screencap the stream you are watching. 

its a legal hell hole, then again downloading torrents isnt any better either tho, its actually worse as you dont even pay CR.

**Comment by maxpiva** [comment] 2015-09-02 00:39
Yes, that is the action of the user. But DMCA in USA forbidde to create any aparatus (software included) capable of removing DRM.

**Comment by AreFinstad** [comment] 2015-09-02 00:43
well is it possible to limit the program to not remove the DRM and just stream instead of downloading? 
just a thought..... but then again, you have prob already tried and thought about that XD

how about splitting up the files? like having the Normal JMM client with no DRM removal and so on and host one or two files somewhere else away from the program with a random name, password and so on.

just my silly thoughts tho :D

**Comment by ElementalCrisis** [comment] 2015-09-02 00:45
Looking around on CrunchyRoll they've made kit clear that their service is for streaming, not downloading. However I found this hosted right here on GitHub. 

https://github.com/Deathspike/crunchyroll.js

**Comment by maxpiva** [comment] 2015-09-02 00:50
Are, Almost imposible, every solution has a custom player, capable of playing DRM, there is a few variations but, coding a video player is out of the question. 
ElementalCrisis nice. But if this program is popular enough. Braindead children can use it. Not a technical person capable of running node.js... It could be problems, also check daisuki and funimation. They seems to be less lax about downloading their streams.

**Comment by AreFinstad** [comment] 2015-09-02 00:54
having something like that Github page has might be nice, but its all code based without a GUI, it would be a pain for most and a hassle for even less. not to mention most people would not even begin to grasp what to do with something like that.  thats why i think building it into JMM is a great idea for the masses. (and speed too IMO as it takes time writing everything you need to start a stream/download)

**Comment by ElementalCrisis** [comment] 2015-09-02 00:58
If adding this functionality inside of JMM I would say don't add the downloading bit. As already mentioned it could cause unforeseen legal problems. The benefit though is you can advertise this feature on places like CrunchyRoll bringing in new users.

**Comment by AreFinstad** [comment] 2015-09-02 01:00
agreed, JMM can always support Shana at the same time, maybe have a link on the streaming part that links you to the shana part of the same series, or maybe somehow build it into one.

**Comment by maxpiva** [comment] 2015-09-04 01:23
It's Up.
https://github.com/maxpiva/AnimeOfflineDownloader

**Comment by ElementalCrisis** [comment] 2017-06-30 08:22
As torrent support is no longer a feature of Shoko, I'm closing this.

**Closed by ElementalCrisis** 2017-06-30 08:22 UTC
Labels: Enhancement - Core Change, In Progress
