### ISSUE TITLE
Dependency Integrity and Permission Check Server Files. (in case of blocked files)

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoServer#630] opened 2017-06-17 21:18 UTC
Importing and Loading Path Browsing window errors out.

Importing doesnt work on any buttons (all buttons on Server, Desktop and WebUI have been tested here) 
Loading up the Path Browsing window on the Server crashes the server (stops working and stops responding) 

its the same error all the time it seems:
`[2017-06-17 02:52:30:059] Error|BackgroundWorker.OnDoWork => ShokoServer.WorkerImport_DoWork => Importer.RunImport_NewFiles System.Exception: Error Opening Local Filesystem
   at Shoko.Server.Models.SVR_ImportFolder.get_FileSystem() in C:\projects\jmmserver\Shoko.Server\Models\SVR_ImportFolder.cs:line 109
   at Shoko.Server.Models.SVR_ImportFolder.get_BaseDirectory() in C:\projects\jmmserver\Shoko.Server\Models\SVR_ImportFolder.cs:line 146
   at Shoko.Server.Importer.RunImport_NewFiles() in C:\projects\jmmserver\Shoko.Server\Import\Importer.cs:line 373
[2017-06-17 02:52:30:062] Error|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => ShokoServer.WorkerImport_DoWork System.Exception: Error Opening Local Filesystem
   at Shoko.Server.Models.SVR_ImportFolder.get_FileSystem() in C:\projects\jmmserver\Shoko.Server\Models\SVR_ImportFolder.cs:line 109
   at Shoko.Server.Models.SVR_ImportFolder.get_BaseDirectory() in C:\projects\jmmserver\Shoko.Server\Models\SVR_ImportFolder.cs:line 146
   at Shoko.Server.Importer.RunImport_DropFolders() in C:\projects\jmmserver\Shoko.Server\Import\Importer.cs:line 310`

[2017-06-17.txt](https://github.com/japanesemediamanager/ShokoServer/files/1082754/2017-06-17.txt)

Attached a log of me trying to click the import button on almost every way i can.
since the browsing window doesnt load then you cant even add paths to the server. you can do this with the Shoko Desktop by manually pasting or typing the path (it does not load the folder browser)

EDIT: forgot to mention it is on Server 3.7.0.1629 downloaded and installed on the 16th of June 2017

**Comment by ElementalCrisis** [comment] 2017-06-17 21:36
Both work for me on latest commit. 

Maybe an error with the daily build?

**Comment by AreFinstad** [comment] 2017-06-17 21:42
was a new version from last night. same happend like a month ago too when i tried it. and that was a fresh daily release and install back then. brand new DB aswell as settings.

**Comment by ElementalCrisis** [comment] 2017-06-17 21:55
New MySQL DB, no issues.

![image](https://user-images.githubusercontent.com/9443295/27256534-e3b81c58-536c-11e7-9ff7-9e8daf190ad0.png)

```[2017-06-17 14:54:06:029] Info|ImportFolderForm.btnSave_Click => ShokoServiceImplementation.SaveImportFolder => ShokoServer.StartWatchingFiles Watching ImportFolder: NA || H:\Anime\
[2017-06-17 14:54:06:029] Info|ImportFolderForm.btnSave_Click => ShokoServiceImplementation.SaveImportFolder => ShokoServer.StartWatchingFiles Parsed ImportFolderLocation: H:\Anime\
[2017-06-17 14:54:06:029] Info|ImportFolderForm.btnSave_Click => ShokoServiceImplementation.SaveImportFolder => ShokoServer.StartWatchingFiles Watching ImportFolder: NA || D:\Anime\
[2017-06-17 14:54:06:029] Info|ImportFolderForm.btnSave_Click => ShokoServiceImplementation.SaveImportFolder => ShokoServer.StartWatchingFiles Parsed ImportFolderLocation: D:\Anime\
[2017-06-17 14:54:10:801] Info|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Hashing File: D:\Anime\Aldnoah Zero - Episode 0 (Count to A-Z) [720p].mkv
[2017-06-17 14:54:14:657] Info|CommandRequest_HashFile.ProcessFile_LocalInfo => SVR_VideoLocal_Place.RefreshMediaInfo => AzureWebAPI.Get_Media Cache HTTP - Getting Media Info From Cache for ED2K: B32C285F9A356D67E01727BEDA868114 Version : 3
[2017-06-17 14:54:14:750] Info|CommandRequest_HashFile.ProcessFile_LocalInfo => SVR_VideoLocal_Place.RefreshMediaInfo => AzureWebAPI.Get_Media Cache HTTP - Getting Media Info From Cache for ED2K: B32C285F9A356D67E01727BEDA868114 - 93.7498
[2017-06-17 14:54:15:630] Info|AniDBHelper.Login => AniDBCommand_Login.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_RESPONSE in 165.9686 ms - 200 ZXymt LOGIN ACCEPTED
 
[2017-06-17 14:54:20:355] Info|AniDBHelper.GetFileInfo => AniDBCommand_GetFileInfo.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_COMMAND: FILE size=339564755&ed2k=B32C285F9A356D67E01727BEDA868114&fmask=7FF8FFF9FE&amask=0000FCC0&s=ZXymt
[2017-06-17 14:54:20:448] Info|AniDBHelper.GetFileInfo => AniDBCommand_GetFileInfo.Process => AniDBUDPCommand.ProcessCommand AniDB UDP - UDP_RESPONSE in 93.749 ms - 320 NO SUCH FILE
 
[2017-06-17 14:54:20:448] Info|CommandRequest_ProcessFile.ProcessCommand => CommandRequest_ProcessFile.ProcessFile_AniDB => AzureWebAPI.Get_CrossRefFileEpisode Cache HTTP - Getting File/Episode Cross Ref From Cache: B32C285F9A356D67E01727BEDA868114
[2017-06-17 14:54:20:480] Info|CommandRequest_ProcessFile.ProcessCommand => CommandRequest_ProcessFile.ProcessFile_AniDB => AzureWebAPI.Get_CrossRefFileEpisode Cache HTTP - Got File/Episode Cross Ref From Cache: B32C285F9A356D67E01727BEDA868114 - 31.2514
[2017-06-17 14:54:20:495] Info|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Hashing File: D:\Anime\Aldnoah.Zero - Vol.06 SP (BD 1280x720 AVC AAC).mp4
[2017-06-17 14:54:29:823] Info|CommandRequest_HashFile.ProcessFile_LocalInfo => SVR_VideoLocal_Place.RefreshMediaInfo => AzureWebAPI.Get_Media Cache HTTP - Getting Media Info From Cache for ED2K: 9C7D8CBEA64116AFABBDF274FFC1CC7F Version : 3
[2017-06-17 14:54:29:854] Info|CommandRequest_HashFile.ProcessFile_LocalInfo => SVR_VideoLocal_Place.RefreshMediaInfo => AzureWebAPI.Get_Media Cache HTTP - Getting Media Info From Cache for ED2K: 9C7D8CBEA64116AFABBDF274FFC1CC7F - 31.2495
```

**Comment by AreFinstad** [comment] 2017-06-17 21:56
using MS SQL 2014 i think. if that would have any say.

**Comment by ElementalCrisis** [comment] 2017-06-17 22:04
Can confirm it's an issue with the daily build itself, not with Shoko Server.

**Comment by da3dsoul** [comment] 2017-06-17 23:59
Ah it's an issue with the build? That'd make sense why I couldn't reproduce it

**Comment by AreFinstad** [comment] 2017-06-25 16:57
this seems to be tied to Windows blocking the .dll files
turning off SmartScreen or unlocking them seems to fix it.

this shouldn't be closed just yet though.

**Comment by AreFinstad** [comment] 2017-06-25 17:08
the user can either unblock the zip itself and then extract it with explorer or use 7zip or winrar.
those 3 are the options to get all files unblocked at once. 

leaving the comment here incase someone has the issue.

**Comment by hidden4003** [comment] 2017-06-25 17:17
I think some checks are needed before we close this to make this case easier to detect in the future, we had this issue several times now and every time it took quite some time to figure out.

**Closed** 2017-06-27 18:22 UTC
Labels: Bug - Low Priority
